version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@16.0.4
  build:
    commands:
      - echo " Building angular project... "
      - ng build --prod
  post-build:
    commands:
      - echo "Update file into S3 buckets..."
      - aw3 s3 sync dist/INF428/ s3://INF428_App --delete